/*
* (c) 2025 World Programming, an Altair Company.
*
* This example illustrates how to generate graphical output
* using the GPLOT procedure.
*
* Use the Output Explorer view to open the resulting HTML output.
*/

GOPTIONS DEVICE=GIF HTEXT=1;

/* Generate some sample data */
DATA stats;
  DO k=1 TO 10;
    DO i=1 TO 10;
      j = i*i+k*k;
      day=TODAY()-i;
      OUTPUT;
    END;
  END;
RUN;

/* Setup some graphical output parameters */
LEGEND2  FRAME SHAPE=BAR(3,1)
         LABEL=('k=kilos' COLOR=red)
         VALUE=(h=1 COLOR=red);
TITLE j=l 'Graphical Output Example Using GPLOT AREAS';
FOOTNOTE1 j=l COLOR=blue 'Generated by Altair SLC '
          j=r 'www.worldprogramming.com';
    ;
AXIS1 LABEL=(j=l 'DATE');
AXIS2 LABEL=('j=jellies' angle=90);
SYMBOL1 VALUE=dot h=.1 i=j;

PATTERN1 V=x5     C=pink;
PATTERN2 V=msolid C=yellow;
PATTERN3 V=msolid C=purple;
PATTERN4 V=l5     C=white;
PATTERN5 V=r1     C=black;

/* Generate the graphical output */
PROC GPLOT DATA=stats GOUT=gout;
  FORMAT day date5.;
  PLOT j*day=k /
    HAXIS=axis1
    VAXIS=axis2
    LEGEND=LEGEND2
    AREAS=11
    VREF= 50 100 150
    NAME="plot_out"
    VMINOR=10;
RUN;

